### ISSUE TITLE
broken VI

### ISSUE THREAD

**Issue by steveball-jki** [fisothemes/LabVIEW-TwinCAT-ADS#2]
FisoThemes\LabVIEW TwinCAT ADS\TwinCAT ADS Class\VIs\Flatten .NET Symbol Information.vi is broken with minor errors

**Comment by fisothemes** [comment]
Hi @steveball-jki 

Thanks for opening the issue. This was fixed in pre-release [1.0.2.6](https://github.com/fisothemes/LabVIEW-TwinCAT-ADS/releases/tag/1.0.2.6). 

However, I will leave this issue open until the next release on vipm.io

**Comment by fisothemes** [comment]
Fixed. See [Release 1.1.3.11](https://github.com/fisothemes/LabVIEW-TwinCAT-ADS/releases/tag/1.1.3.11).
